FROM node:16.19.1 as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

RUN npm run build-storybook

FROM sthanasis/esupply:latest

COPY --from=build /app/storybook-static /app/storybook-static