FROM node:16.18.1 as build

WORKDIR /app

COPY package.json .
COPY . .

RUN npm install
RUN npm run build-storybook

FROM sthanasis/esupply:latest

COPY --from=build /app/storybook-static /app/storybook-static